services:
  - type: web
    name: ratechecker
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install --only-binary=:all: -r requirements.txt
      python -m playwright install --with-deps chromium
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
